### ISSUE TITLE
[BUG] [URGENT] Multiple Instances of IDOR Vulnerability Discovered: 

### ISSUE THREAD

**Issue by ambushneupane** [NebulaAnish/Transaction-App#1]
Hello @NebulaAnish , 
During my testing, I discovered  Insecure Direct Object Reference (IDOR) vulnerabilities in the website in multiple endpoints. For the ease of reproduction I have divided them into two groups. 

(NOTE:- NUMBER IS just a simple number like 1,2,3,....)  

1) IDOR in /transaction/ endpoint
  a) A simple authenticated GET request to  /transaction   /{Number} leads to information Disclosure which means that an attacker can  view the sensitive transaction information of any user by accessing this endpoint.

  b) POST Request to  /transaction/{Number}/update updates the transaction of a user. There's No security Implementation here which means an attacker can modify the transactions of any user by sending a POST request to this endpoint
  
c) In  POST Request to  /transaction/{Number}/delete, an
 Attacker can delete transactions of any user on the platform using this endpoint, leading to data loss and potential disruptions.

2) IDOR in /profileedit/{NUMBER}
a) GET request to /profileedit/{NUMBER} leads to information Disclosure
b) With POST request to /proifleedit/{NUMBER} an attacker can modify any users (including admin's) information (email,username,firstname, lastname) 

Considering the severity of these vulnerabilities, immediate action is imperative to protect your users' data and prevent any misuse of the platform.

I hope it will be fixed soon! Thanks, 
Ambush Neupane

**Comment by nebulaanish** [comment]
The issue was fixed in the recent commit b02fa48 & 5b692b9 by using dispatch() function to check whether the user has the privilege to the activity that he/she is attempting to access or not.
